Allow logging to /dev/stderr
sclorg/postgresql-container pull request #366
Opened 2020-03-23 08:14 UTC by hhorak

For easier debugging, it should be pretty easy to switch daemon to log into the /dev/stderr.
This adds such a feature by setting POSTGRESQL_LOG_DESTINATION environment variable to /dev/stderr.

This should address #353.

2020-03-24 09:46 UTC, phracek commented on test/run_test
> +  while f in "${data_dir}"/userdata/log/postgresql-*.log ] ; do
```suggestion
  while f in [ "${data_dir}"/userdata/log/postgresql-*.log ] ; do
```

2020-03-24 09:52 UTC, phracek commented on test/run_test
> +  while f in "${data_dir}"/userdata/log/postgresql-*.log ] ; do
```suggestion
  for f in "${data_dir}"/userdata/log/postgresql-*.log ; do
```

https://www.cyberciti.biz/faq/bash-loop-over-file/

2020-03-24 10:59 UTC, hhorak commented on test/run_test
> +  while f in "${data_dir}"/userdata/log/postgresql-*.log ] ; do
Thanks, fixed.

2020-03-26 08:17 UTC, phracek commented
[test]

2020-03-26 09:19 UTC, pkubatrh commented
centos7 failure will be fixed by https://github.com/sclorg/postgresql-container/pull/368

2020-03-26 10:56 UTC, phracek commented
@hhorak rhel8 test is failing by
```bash
+ echo 'psql -U nonexistent'
++ get_cid pg-test-logging
++ local id=pg-test-logging
++ shift
+++ cat /tmp/tmp.nwSOqgiZvspostgresql_test_cidfiles/pg-test-logging
++ echo b9893aa670ad049bae5a6db4fa5f6a2116c7fb9b38d5b79e75c4111f2e5f06b6
+ docker exec -i b9893aa670ad049bae5a6db4fa5f6a2116c7fb9b38d5b79e75c4111f2e5f06b6 bash
+ sleep 1
+ grep -q 'FATAL:  role "nonexistent" does not exist'
++ get_cid pg-test-logging
++ local id=pg-test-logging
++ shift
+++ cat /tmp/tmp.nwSOqgiZvspostgresql_test_cidfiles/pg-test-logging
++ echo b9893aa670ad049bae5a6db4fa5f6a2116c7fb9b38d5b79e75c4111f2e5f06b6
+ docker logs b9893aa670ad049bae5a6db4fa5f6a2116c7fb9b38d5b79e75c4111f2e5f06b6
ERROR: the container log does not include expected error message
+ echo 'ERROR: the container log does not include expected error message'
```

Unfortunately, I am not able to reproduce it locally :(  Locally all tests are passing.

2020-04-21 12:30 UTC, phracek commented
[test]

2020-04-22 08:02 UTC, phracek commented
[test]

2020-05-04 10:19 UTC, pkubatrh commented
Needs a rebase now that #368 is merged

2020-06-17 12:31 UTC, pkubatrh commented
Rebased [test-openshift]

2020-06-17 13:38 UTC, phracek commented
[test]

2021-03-11 21:26 UTC, fridex commented
A friendly ping - will this be eventually applied? It would definitely help us.

2021-03-12 13:27 UTC, hhorak commented
> A friendly ping - will this be eventually applied? It would definitely help us.

That's great feedback, thanks, we'll try to finish it.

2021-11-30 08:00 UTC, phracek commented
Let's try to run all tests once more.

[test-all]

2022-05-09 13:12 UTC, phracek commented
[test-all]

2023-02-22 09:50 UTC, pkubatrh commented
Lets try to revisit and make sure this gets merged.

2023-03-01 08:28 UTC, fila43 commented
[test]

2023-03-01 08:48 UTC, hhorak commented
Rebased.

2023-03-01 08:49 UTC, hhorak commented
[test]

2023-03-01 09:32 UTC, hhorak commented
Test for this had some issues, so let's try again after improving it a bit.
[test]

2023-03-01 09:40 UTC, hhorak commented
[test]

2023-03-01 14:33 UTC, phracek commented
RHEL8 tests are failing for this reason:

```bash
-----------------------------------------------
Running test run_logging_test (starting at 2023-03-01 06:04:51-05:00) ... 
-----------------------------------------------
640a6a2bef4835f14cf7403051c5a2d4e544647f643926977ac84fb9806f6889
Created container 640a6a2bef4835f14cf7403051c5a2d4e544647f643926977ac84fb9806f6889
Error: non zero exit code: 2: OCI runtime error
Error: non zero exit code: 2: OCI runtime error
Error: read unixpacket @->/var/run/libpod/socket/d0e9d591a8da0bcdbc8d9657fb9b3fdb958f81162accc0d33637c7ffe2de3973/attach: read: connection reset by peer
ERROR: the container log does not include expected error message
Test for image 'rhel8/postgresql-13:1' FAILED (exit code: 1)

[snipped]
 [PASSED] for 'postgresql-container_tests' run_pgaudit_test (00:00:05)
 [FAILED] for 'postgresql-container_tests' run_logging_test (00:00:05)

```

What about adding more logs for debugging issues?

2023-03-09 13:27 UTC, fila43 commented
[test]

2023-03-22 12:02 UTC, phracek commented
@hhorak Please have a look at RHEL8 tests. They are failing on:

```bash
 [FAILED] for 'postgresql-container_tests' run_logging_test (00:00:05). 
```

May be more logs for traces would be fine.

2023-03-22 12:03 UTC, phracek requested changes
Please rebase common module and add more traces to the latest test.

2023-03-22 12:04 UTC, fila43 commented
@phracek I see  [FAILED] for 'postgresql-container_tests' run_master_restart_test (00:01:14)

2023-03-27 07:21 UTC, fila43 commented
The investigation in https://github.com/sclorg/postgresql-container/pull/503 leads me to the conclusion. Added functionality works as expected, and it's proven by passing all tests except RHEL8. Logging to stderr also should work in the case of RHEL8. Unfortunately, RHEL8 uses podman version 1.6.4. This version raises error `Error: non zero exit code: 2: OCI runtime error` for the `docker exec` command.

2023-03-27 07:42 UTC, hhorak commented
@fila43 I see the `docker exec` exit code should not matter, as the line ends with ` || :` -- can you explain why it might make the difference?

2023-03-27 10:12 UTC, zmiklank commented
[test]

2023-03-27 20:34 UTC, fila43 commented
[test]

2023-03-28 09:32 UTC, fila43 commented
It seems that `master_restart_test` randomly fails. Since it isn't related to this PR, could we merge it @hhorak @zmiklank? I would prefer to fix the failing test in a separate PR later. Because it happens only occasionally and only within GitHub CI, it makes investigating the problem tricky.

2023-03-28 10:13 UTC, zmiklank commented
> It seems that `master_restart_test` randomly fails. Since it isn't related to this PR, could we merge it @hhorak @zmiklank? I would prefer to fix the failing test in a separate PR later. Because it happens only occasionally and only within GitHub CI, it makes investigating the problem tricky.

I agree to fix the test which is not connected to this PR separately. However I can not give lgtm to this PR now, as I did not review it yet.

2023-03-28 10:25 UTC, zmiklank commented
> From my point of view, the PR is LGTM. There is only one unrelated problem with random failures. But I am ok to wait for your review. Thanks

You do not really need to wait for my review :).

2023-03-28 11:28 UTC, merged