Use generic run tests
sclorg/postgresql-container pull request #464
Opened 2022-09-16 08:28 UTC by zmiklank

2022-09-16 08:38 UTC, zmiklank commented
[test-all]

2022-09-21 07:24 UTC, phracek commented on test/run_test
> +CID_FILE_DIR=$(mktemp --suffix=postgresql_test_cidfiles -d)
Why this is needed?

2022-09-21 07:25 UTC, phracek requested changes
Please look at my comments. I don't think, renaming variable is needed.

2022-09-21 07:25 UTC, phracek commented on test/run_test
> +CID_FILE_DIR=$(mktemp --suffix=postgresql_test_cidfiles -d)
This does not break functionality. And only cosmetic issue does not make sense to me.

2022-09-21 07:42 UTC, phracek commented
[test]

2022-09-21 08:26 UTC, phracek commented
RHEL-9 Unsubscribed host is removed by #466

2022-09-21 09:46 UTC, phracek requested changes

2022-09-21 09:46 UTC, phracek commented on test/run_test
> -  docker stop "$(get_cid $container_name)" >/dev/null
Why `docker stop` is removed from here?

2022-09-21 10:01 UTC, zmiklank commented on test/run_test
> -  docker stop "$(get_cid $container_name)" >/dev/null
Because it is done in `ct_cleanup`.

2022-09-21 11:04 UTC, phracek approved these changes
LGTM. Thanks for your responses. Tests are passing.

2022-09-21 11:05 UTC, merged