Fix distgen generation
sclorg/postgresql-container pull request #475
Opened 2022-10-19 08:57 UTC by zmiklank

This commit should get the source code to the state before introduction of the new generator.

2022-10-19 10:55 UTC, zmiklank commented
@fila43 Could you please check, if all supported versions are available in the sources now?

2022-10-20 10:49 UTC, zmiklank commented
[test-all]

2022-10-20 11:02 UTC, phracek requested changes
Based on the https://src.fedoraproject.org/rpms/postgresql version 10 is out of scope for Fedora. In Fedora 35 we have version 13. Therefore Dockerfile.fedora for version `10` does not make sense.

Postgresql 10 will have EOL in December 2022 for RHEL7 and therefore I do not know if want to have it. But I am not against it.

2022-10-20 11:17 UTC, phracek requested changes
Some nit picks.

2022-10-20 11:17 UTC, phracek commented on 12/Dockerfile.centos7
> +FROM quay.io/centos7/s2i-core-centos7
```suggestion
FROM quay.io/centos7/s2i-core-centos7:latest
```

2022-10-20 11:17 UTC, phracek commented on 12/Dockerfile.centos7
> +FROM quay.io/centos7/s2i-core-centos7
or `:centos7`. This could be better.

2022-10-20 11:17 UTC, phracek commented on 13/Dockerfile.centos7
> +FROM quay.io/centos7/s2i-core-centos7
```suggestion
FROM quay.io/centos7/s2i-core-centos7:centos7
```

2022-10-20 11:53 UTC, merged