deprecate c8s images, as EOL for c8s is 31th of May 2024
sclorg/postgresql-container pull request #567
Opened 2024-05-22 07:31 UTC by zmiklank

2024-06-03 08:59 UTC, phracek commented
[test]

2024-06-03 09:01 UTC, phracek commented on .github/workflows/build-and-push.yml
>            - dockerfile: "15/Dockerfile.fedora"
This version is present https://src.fedoraproject.org/rpms/postgresql15

2024-06-03 09:01 UTC, phracek commented on .github/workflows/build-and-push.yml
>            - dockerfile: "16/Dockerfile.fedora"
This version is present https://src.fedoraproject.org/rpms/postgresql16

2024-06-03 09:02 UTC, phracek commented on .github/workflows/build-and-push.yml
>            - dockerfile: "13/Dockerfile.fedora"
This can be dropped https://src.fedoraproject.org/rpms/postgresql12

2024-06-03 09:02 UTC, phracek requested changes
I think we can drop some Fedora versions. @fila43 What do you think?

2024-06-03 09:18 UTC, zmiklank commented on .github/workflows/build-and-push.yml
>            - dockerfile: "12/Dockerfile.fedora"
I think we should do regular Fedora cleanup again - migrate all images to new Fedoras, and remove unsupported images. There will be more outdated content I think. I suggest doing it in different PR.

2024-06-04 07:12 UTC, phracek commented on .github/workflows/build-and-push.yml
>            - dockerfile: "13/Dockerfile.fedora"
Issue is here: https://github.com/sclorg/postgresql-container/issues/570

2024-06-04 07:12 UTC, phracek commented on .github/workflows/build-and-push.yml
>            - dockerfile: "12/Dockerfile.fedora"
Issue is here: https://github.com/sclorg/postgresql-container/issues/570

2024-06-04 10:49 UTC, phracek approved these changes
LGTM.

2024-06-04 10:49 UTC, merged