Document all test functions and organize them together inside run_test
sclorg/postgresql-container pull request #598
Opened 2024-10-23 13:27 UTC by SlouchyButton

All test functions are now ordered in the same way, they are ordered in the `TEST_LIST` variable. Helper functions that were previously between the test functions are now on top of the run_test file.

The diff is very chaotic, but since some function moved places in the file, I don't see a way to make the review easier.

2024-10-23 13:30 UTC, SlouchyButton commented
[test]

2024-11-01 11:50 UTC, phracek requested changes
Before my review, It would be nice to separate the pull request to several commits. It is hard to review it.

2024-11-01 19:52 UTC, SlouchyButton commented
Tried to split all 3 steps (annotating, grouping, ordering) into different commits. It's still a bit chaotic diff, but should be at least linked to the specific step taken.

2024-11-19 08:36 UTC, phracek approved these changes
LGTM. Thanks for this pull request. The description and separation to more commits, make this pull request more easier to review.

2024-11-20 12:19 UTC, merged